server:
  port: 8202

spring:
  image:
    storage:
      path: "/home/agraich/Documents/3A/projet s5/backend_adoption/services/animal-annonce/uploads/images"
  sql:
    init:
      mode: always
  datasour ce:
    url: jdbc:postgresql://localhost:5432/annonce-management
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hibernate.default_schema: public

    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
      springframework:
        orm:
          jpa: DEBUG
    root: INFO
