server:
  port: 8202

spring:
  image:
    storage:
      path: "./uploads/images"
  datasource:
    url: jdbc:postgresql://localhost:5432/annonce-management
    username: root
    password: password
    driver-class-name: org.postgresql.Driver
    jpa:
      show-sql: true
      properties:
        hibernate:
          format_sql: true
      hibernate:
        ddl-auto: create
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB



eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE
