spring:
  cloud:
    gateway:
      routes:
        - id: animal-annonce-service
          uri: lb://animal-annonce-service
          predicates:
            - Path=/api/animal-annonces/**, /api/adoptions/** , /images/** , /animal-annonce/uploads/images/**
          filters:
            - name: AddRequestHeader
              args:
                name: "Access-Control-Allow-Origin"
                value: "http://localhost:5173" # Autoriser votre front-end
            - name: AddRequestHeader
              args:
                name: "Access-Control-Allow-Methods"
                value: "GET, POST, PUT, DELETE, OPTIONS"
            - name: AddRequestHeader
              args:
                name: "Access-Control-Allow-Headers"
                value: "Content-Type, Authorization"

        - id: user-management-service
          uri: lb://user-management-service
          predicates:
            - Path=/api/auth/**, /api/users/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true
