server:
  port: 8210

spring:
  data:
    mongodb:
      username: mongodatabase
      password: password
      host: localhost
      port: 27017
      database: chat_app
      authentication-database: admin

eureka:
  client:
    region: us-east-1
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    registerWithEureka: true
    fetchRegistry: true
  instance:
    preferIpAddress: true


logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: TRACE

    springframework:
      cloud:
        netflix:
          eureka: DEBUG
      security: DEBUG   # Correction ici
      web:
        socket: DEBUG
    com:
      netflix:
        discovery: DEBUG
